print("int", "2, 4")
print("float", "1.6, 5.0")
print("/", "always return float")
print("//", "floor division (int)")
print("%", "remainder")
print("**", "exponentiation")
print("_", "last printed expression (interactive mode)")
print("round(3.1415, 2)", "round to 2 decimal places")
print("Fraction, Decimal, complex", ": other number types")
print("j, J", ": imaginary part")
